function Build-PolyJson([double]$lat, [double]$lng, [double]$dLat, [double]$dLng) {
  $M = [math]
  $p1lat = $M::Round($lat + $dLat, 3);       $p1lng = $M::Round($lng, 3)
  $p2lat = $M::Round($lat + $dLat*0.7, 3);   $p2lng = $M::Round($lng + $dLng*0.7, 3)
  $p3lat = $M::Round($lat, 3);                $p3lng = $M::Round($lng + $dLng, 3)
  $p4lat = $M::Round($lat - $dLat*0.7, 3);   $p4lng = $M::Round($lng + $dLng*0.7, 3)
  $p5lat = $M::Round($lat - $dLat, 3);        $p5lng = $M::Round($lng, 3)
  $p6lat = $M::Round($lat - $dLat*0.7, 3);   $p6lng = $M::Round($lng - $dLng*0.7, 3)
  $p7lat = $M::Round($lat, 3);                $p7lng = $M::Round($lng - $dLng, 3)
  $p8lat = $M::Round($lat + $dLat*0.7, 3);   $p8lng = $M::Round($lng - $dLng*0.7, 3)
  return "[[$p1lat, $p1lng], [$p2lat, $p2lng], [$p3lat, $p3lng], [$p4lat, $p4lng], [$p5lat, $p5lng], [$p6lat, $p6lng], [$p7lat, $p7lng], [$p8lat, $p8lng]]"
}

$NL = [System.Environment]::NewLine

$newLocalities = @(
  # OLD CITY / CENTRAL (11)
  @{ slug="charminar"; name="Charminar"; lat=17.360; lng=78.473; dLat=0.010; dLng=0.012; zone="Central"; score=52; cat="Established"; infra=58; pop=75; sat=35; rera=25; emp=60; pv=45; gs=62; conn=60; amen=72; ecom=68; ent=65; green=28; pr="Rs3,500-6,500/sqft"; yoy=8; dc="partial"; sv=6; h1="Historic Charminar  -  UNESCO-nominated monument anchors old city tourism and commerce"; h2="GHMC Smart City upgrades on Laad Bazaar corridor underway through 2027"; h3="Dense heritage residential with strong artisan economy: bangles, pearls, fabric"; h4="Heritage zone restrictions limit new vertical supply  -  prices floor above old city average" }
  @{ slug="afzalgunj"; name="Afzalgunj"; lat=17.378; lng=78.474; dLat=0.008; dLng=0.010; zone="Central"; score=55; cat="Established"; infra=60; pop=72; sat=38; rera=30; emp=65; pv=50; gs=60; conn=65; amen=68; ecom=70; ent=62; green=25; pr="Rs3,200-6,000/sqft"; yoy=7; dc="partial"; sv=6; h1="Major wholesale market hub  -  hardware, textiles, chemicals on Afzalgunj Bridge corridor"; h2="Musi River front development plan includes park and walkway by 2027"; h3="Excellent TSRTC bus connectivity to all city zones from central depot"; h4="Old city commercial backbone with stable long-term rental demand" }
  @{ slug="sultan-bazaar"; name="Sultan Bazaar"; lat=17.385; lng=78.471; dLat=0.008; dLng=0.010; zone="Central"; score=58; cat="Established"; infra=62; pop=70; sat=40; rera=32; emp=68; pv=52; gs=58; conn=68; amen=70; ecom=72; ent=65; green=22; pr="Rs4,000-7,000/sqft"; yoy=9; dc="partial"; sv=6; h1="Central commercial district  -  books, hardware, electronics wholesale cluster"; h2="Metro Blue Line Nampally station 800m  -  strong walk-to-transit score"; h3="Koti women's college vicinity drives consistent retail footfall"; h4="Office and showroom demand stable despite e-commerce pressure" }
  @{ slug="hussaini-alam"; name="Hussaini Alam"; lat=17.361; lng=78.463; dLat=0.008; dLng=0.010; zone="Central"; score=48; cat="Emerging"; infra=50; pop=68; sat=35; rera=28; emp=55; pv=42; gs=55; conn=55; amen=62; ecom=62; ent=55; green=25; pr="Rs2,800-5,200/sqft"; yoy=7; dc="partial"; sv=5; h1="Dense old city residential  -  high occupancy, low vacancy near Charminar"; h2="Aga Khan Trust conservation projects improving heritage streetscape"; h3="Pearl and bangle trade within walking distance supports local employment"; h4="Road widening under Musi Riverfront Development Plan to improve access" }
  @{ slug="yakutpura"; name="Yakutpura"; lat=17.346; lng=78.487; dLat=0.010; dLng=0.012; zone="Central"; score=47; cat="Emerging"; infra=48; pop=65; sat=33; rera=25; emp=52; pv=40; gs=52; conn=52; amen=60; ecom=60; ent=50; green=30; pr="Rs2,500-4,800/sqft"; yoy=7; dc="partial"; sv=5; h1="Old city south zone  -  rapidly densifying with new housing demand"; h2="GHMC road improvement connecting to Dilsukhnagar flyover in progress"; h3="Large Muslim population drives demand for ground-floor commercial units"; h4="Close to Charminar heritage zone  -  tourist spill-over benefits commerce" }
  @{ slug="chaderghat"; name="Chaderghat"; lat=17.374; lng=78.482; dLat=0.008; dLng=0.010; zone="Central"; score=50; cat="Established"; infra=55; pop=62; sat=38; rera=30; emp=58; pv=45; gs=55; conn=60; amen=65; ecom=65; ent=58; green=32; pr="Rs3,000-5,500/sqft"; yoy=8; dc="partial"; sv=6; h1="Musi River bridge area  -  strategic link between old and new city"; h2="Osmania General Hospital proximity creates sustained medical economy"; h3="TSRTC depot ensures strong bus connectivity to Secunderabad and suburbs"; h4="Heritage residential demand rising as old city regeneration gains momentum" }
  @{ slug="moghalpura"; name="Moghalpura"; lat=17.373; lng=78.506; dLat=0.010; dLng=0.012; zone="Central"; score=44; cat="Industrial"; infra=48; pop=58; sat=32; rera=20; emp=65; pv=38; gs=50; conn=55; amen=55; ecom=60; ent=40; green=28; pr="Rs2,500-4,500/sqft"; yoy=6; dc="partial"; sv=5; h1="Industrial cluster: workshops, fabrication, auto ancillary  -  high employment density"; h2="Proximity to Secunderabad Railway Yard historically drove manufacturing base"; h3="Emerging mixed-use redevelopment as industrial plots repurpose to commercial"; h4="Below-average green cover  -  livability constraint on residential premiums" }
  @{ slug="bahadurpura"; name="Bahadurpura"; lat=17.352; lng=78.476; dLat=0.010; dLng=0.012; zone="Central"; score=46; cat="Emerging"; infra=50; pop=64; sat=32; rera=25; emp=55; pv=40; gs=52; conn=54; amen=60; ecom=62; ent=48; green=28; pr="Rs2,600-5,000/sqft"; yoy=7; dc="partial"; sv=5; h1="South old city corridor  -  growing residential demand from young professionals"; h2="Close to Falaknuma Palace and Nizam heritage tourism zone"; h3="GHMC water supply improvements under Musi Riverfront project"; h4="Affordable price point attracting first-time buyers priced out of Falaknuma" }
  @{ slug="rein-bazaar"; name="Rein Bazaar"; lat=17.382; lng=78.476; dLat=0.007; dLng=0.009; zone="Central"; score=54; cat="Established"; infra=58; pop=68; sat=38; rera=30; emp=62; pv=48; gs=56; conn=65; amen=66; ecom=70; ent=60; green=22; pr="Rs3,200-6,000/sqft"; yoy=8; dc="partial"; sv=6; h1="Central commercial node  -  electrical goods, wholesale trade and retail"; h2="Adjacent to Nampally Exhibition Grounds  -  event-driven rental premium"; h3="Well-connected via MMTS Nampally Station within walking distance"; h4="Stable commercial demand supported by government offices nearby" }
  @{ slug="dabirpura"; name="Dabirpura"; lat=17.365; lng=78.488; dLat=0.008; dLng=0.010; zone="Central"; score=48; cat="Emerging"; infra=50; pop=62; sat=32; rera=22; emp=55; pv=42; gs=52; conn=55; amen=60; ecom=62; ent=48; green=28; pr="Rs2,800-5,000/sqft"; yoy=7; dc="partial"; sv=5; h1="Old city east  -  dense Muslim residential with strong community fabric"; h2="Musi River development master plan includes greening of Dabirpura bank"; h3="Small workshops and cottage industry provide stable local employment"; h4="Rising demand for mid-range housing from old city service workers" }
  @{ slug="aghapura"; name="Aghapura"; lat=17.399; lng=78.484; dLat=0.008; dLng=0.010; zone="Central"; score=55; cat="Emerging"; infra=58; pop=60; sat=45; rera=38; emp=55; pv=50; gs=58; conn=62; amen=62; ecom=65; ent=55; green=30; pr="Rs3,000-5,500/sqft"; yoy=8; dc="partial"; sv=6; h1="Transition zone between Secunderabad and old city  -  rapidly upgrading"; h2="Metro station Musheerabad within 1.2km improves transit connectivity"; h3="Growing commercial strip along Aghapura Road: restaurants, clinics, retail"; h4="Investor interest rising as nearby Malkajgiri corridor appreciates" }
  # NORTH (12)
  @{ slug="warasiguda"; name="Warasiguda"; lat=17.468; lng=78.511; dLat=0.008; dLng=0.010; zone="North"; score=67; cat="Established"; infra=70; pop=72; sat=65; rera=62; emp=68; pv=65; gs=65; conn=72; amen=70; ecom=75; ent=65; green=38; pr="Rs4,500-7,500/sqft"; yoy=10; dc="partial"; sv=7; h1="Secunderabad residential belt  -  consistent demand from defense and govt employees"; h2="Excellent MMTS connectivity: Malkajgiri and Secunderabad stations within 2km"; h3="Mature social infrastructure: 5 hospitals, 12 schools within 3km"; h4="Limited land availability creates steady price appreciation above city average" }
  @{ slug="tirumalagiri"; name="Tirumalagiri"; lat=17.455; lng=78.506; dLat=0.009; dLng=0.011; zone="North"; score=70; cat="Established"; infra=72; pop=70; sat=68; rera=55; emp=75; pv=62; gs=70; conn=70; amen=72; ecom=74; ent=65; green=45; pr="Rs5,000-8,500/sqft"; yoy=11; dc="partial"; sv=7; h1="Defense colony  -  Army Service Corps HQ ensures stable high-income resident base"; h2="Premium residential enclave with wide roads and well-maintained infrastructure"; h3="CRPF and Army establishments drive consistent demand for rental housing"; h4="Low crime, high greenery  -  top-tier livability in North Hyderabad" }
  @{ slug="mettuguda"; name="Mettuguda"; lat=17.461; lng=78.516; dLat=0.008; dLng=0.010; zone="North"; score=66; cat="Established"; infra=68; pop=70; sat=62; rera=58; emp=65; pv=62; gs=65; conn=70; amen=68; ecom=72; ent=62; green=38; pr="Rs4,500-7,500/sqft"; yoy=10; dc="partial"; sv=7; h1="Railway colony residential area  -  stable demand from SCR employees"; h2="Mettuguda MMTS station provides direct Secunderabad connection in 8 minutes"; h3="Well-planned colony layout with parks and community halls"; h4="Redevelopment potential as old SCR quarters transition to private housing" }
  @{ slug="karkhana"; name="Karkhana"; lat=17.452; lng=78.499; dLat=0.009; dLng=0.011; zone="North"; score=62; cat="Industrial"; infra=65; pop=60; sat=60; rera=50; emp=80; pv=55; gs=60; conn=68; amen=60; ecom=68; ent=52; green=30; pr="Rs3,800-6,500/sqft"; yoy=9; dc="partial"; sv=6; h1="Mixed industrial-residential: workshops, auto parts, food processing cluster"; h2="South Central Railway workshop (largest railway workshop in India) anchors employment"; h3="Ongoing transition to commercial: warehousing and light manufacturing exiting"; h4="Affordable compared to Secunderabad  -  attracting transit-oriented residential" }
  @{ slug="west-marredpally"; name="West Marredpally"; lat=17.448; lng=78.491; dLat=0.008; dLng=0.010; zone="North"; score=69; cat="Established"; infra=70; pop=72; sat=65; rera=62; emp=68; pv=68; gs=65; conn=72; amen=72; ecom=76; ent=68; green=40; pr="Rs5,000-8,000/sqft"; yoy=11; dc="partial"; sv=7; h1="Premium Secunderabad residential  -  proximity to Cantonment drives demand"; h2="Multiple private schools and colleges keep family occupancy high"; h3="Well-connected by TSRTC to IT corridors  -  dual-income family preferred address"; h4="Limited new supply in this zone pushes prices above Secunderabad baseline" }
  @{ slug="mahendra-hills"; name="Mahendra Hills"; lat=17.441; lng=78.513; dLat=0.008; dLng=0.010; zone="North"; score=72; cat="Established"; infra=72; pop=68; sat=68; rera=60; emp=70; pv=72; gs=68; conn=68; amen=70; ecom=72; ent=68; green=55; pr="Rs5,500-9,000/sqft"; yoy=12; dc="partial"; sv=7; h1="Elevated terrain with Secunderabad Cantonment views  -  premium lifestyle address"; h2="Low density, wide roads, heritage bungalows on large plots"; h3="Favored by defense officers and senior corporate professionals"; h4="Rocky terrain limits densification  -  natural supply constraint preserves value" }
  @{ slug="shamirpet"; name="Shamirpet"; lat=17.591; lng=78.530; dLat=0.015; dLng=0.018; zone="North"; score=58; cat="Emerging"; infra=62; pop=45; sat=68; rera=55; emp=42; pv=65; gs=72; conn=48; amen=42; ecom=52; ent=38; green=75; pr="Rs1,800-3,500/sqft"; yoy=18; dc="partial"; sv=6; h1="Eco resort and film studio belt  -  Ramoji Film City adjacent drives tourism economy"; h2="HMDA approved layouts gaining traction as north Hyderabad expands"; h3="Hyderabad Deer Park and Lake create strong weekend tourism footfall"; h4="Fastest appreciating micro-zone in north Hyderabad outer ring at 18% YoY" }
  @{ slug="gundlapochampally"; name="Gundlapochampally"; lat=17.553; lng=78.498; dLat=0.012; dLng=0.014; zone="North"; score=74; cat="High Growth"; infra=78; pop=55; sat=80; rera=70; emp=82; pv=75; gs=78; conn=65; amen=55; ecom=65; ent=48; green=55; pr="Rs3,500-6,500/sqft"; yoy=20; dc="partial"; sv=7; h1="Amazon, Capgemini, TCS offices within 3km  -  strong IT employment anchor"; h2="Outer Ring Road access at Medchal junction, 18 minutes to RGIA"; h3="HMDA master plan designates zone for IT and knowledge sector expansion"; h4="Fastest growing north corridor: 20% YoY driven by tech park absorption" }
  @{ slug="bonthapally"; name="Bonthapally"; lat=17.621; lng=78.388; dLat=0.020; dLng=0.025; zone="North"; score=56; cat="Emerging"; infra=62; pop=48; sat=65; rera=58; emp=45; pv=62; gs=68; conn=45; amen=40; ecom=50; ent=30; green=65; pr="Rs1,500-3,200/sqft"; yoy=16; dc="partial"; sv=6; h1="HMDA satellite township  -  1,200-acre integrated development under construction"; h2="ORR access and proposed MMTS extension make this a long-horizon land play"; h3="Educational institutions and pharma SEZ land use notified in master plan"; h4="Lowest price point in north Hyderabad with HMDA-backed infrastructure" }
  @{ slug="turkapally"; name="Turkapally"; lat=17.570; lng=78.450; dLat=0.018; dLng=0.022; zone="North"; score=48; cat="Emerging"; infra=50; pop=40; sat=55; rera=42; emp=38; pv=55; gs=60; conn=42; amen=35; ecom=45; ent=25; green=68; pr="Rs1,200-2,500/sqft"; yoy=15; dc="estimated"; sv=5; h1="Rural north  -  transitioning to peri-urban as Medchal spreads outward"; h2="ORR Patancheru-Kompally corridor development drives land speculation"; h3="Proposed pharma cluster expansion from nearby Turkapally IDA zone"; h4="High risk-return ratio for long-horizon (5+ year) land banking" }
  @{ slug="keesaragutta"; name="Keesaragutta"; lat=17.527; lng=78.508; dLat=0.015; dLng=0.018; zone="North"; score=52; cat="Emerging"; infra=55; pop=42; sat=58; rera=45; emp=40; pv=58; gs=62; conn=45; amen=38; ecom=50; ent=35; green=65; pr="Rs1,500-3,000/sqft"; yoy=14; dc="estimated"; sv=5; h1="Keesaragutta Shiva temple drives 1M+ pilgrims annually  -  religious tourism base"; h2="Medchal-Malkajgiri district HQ nearby  -  government employment anchor"; h3="Connectivity improving via NH 44 and proposed ORR spur road"; h4="Tourism economy limits heavy industrial pressure  -  livable outer periphery" }
  @{ slug="pashamylaram"; name="Pashamylaram"; lat=17.498; lng=78.330; dLat=0.015; dLng=0.018; zone="North"; score=62; cat="High Growth"; infra=65; pop=50; sat=68; rera=58; emp=72; pv=62; gs=68; conn=55; amen=45; ecom=58; ent=35; green=50; pr="Rs2,200-4,500/sqft"; yoy=17; dc="partial"; sv=6; h1="IDA Pashamylaram industrial cluster  -  pharma, chemicals, auto-ancillary hub"; h2="ORR junction at Patancheru ensures logistics connectivity to all city zones"; h3="HMDA approved residential layouts absorbing pharma workforce housing demand"; h4="Industrial zone boundary creates clear commercial anchor  -  17% appreciation YoY" }
  # EAST (11)
  @{ slug="nagole"; name="Nagole"; lat=17.384; lng=78.574; dLat=0.010; dLng=0.012; zone="East"; score=71; cat="Established"; infra=72; pop=68; sat=68; rera=65; emp=65; pv=68; gs=68; conn=80; amen=68; ecom=75; ent=65; green=38; pr="Rs4,500-7,500/sqft"; yoy=12; dc="partial"; sv=7; h1="Metro Line 1 terminal  -  direct connectivity to Miyapur in 45 minutes"; h2="Nagole depot and IT corridor junction drive mid-segment residential demand"; h3="Multiple office parks within 5km absorb software professional housing"; h4="Transit-oriented appreciation: 12% YoY anchored by Metro end-station premium" }
  @{ slug="jawaharnagar"; name="Jawaharnagar"; lat=17.354; lng=78.631; dLat=0.015; dLng=0.018; zone="East"; score=52; cat="Emerging"; infra=55; pop=48; sat=58; rera=45; emp=48; pv=55; gs=60; conn=48; amen=42; ecom=52; ent=35; green=55; pr="Rs1,800-3,500/sqft"; yoy=13; dc="partial"; sv=6; h1="TSPCB garbage dumping zone transition to eco-park under Telangana green mandate"; h2="ORR access and Outer East corridor industrial demand driving land value recovery"; h3="Budget residential demand from LB Nagar IT workers seeking affordable options"; h4="Long-term land banking play: environmental remediation adds 4-5 year horizon" }
  @{ slug="rampally"; name="Rampally"; lat=17.437; lng=78.620; dLat=0.015; dLng=0.018; zone="East"; score=55; cat="Emerging"; infra=58; pop=52; sat=62; rera=48; emp=50; pv=58; gs=62; conn=50; amen=45; ecom=55; ent=38; green=60; pr="Rs1,800-3,800/sqft"; yoy=15; dc="partial"; sv=6; h1="Emerging east satellite  -  Keesara municipality growth front absorbing Medchal overflow"; h2="Close to proposed Rampally industrial park in Telangana industrial policy"; h3="Affordable plotted development attracting end-users from Kapra and Ghatkesar"; h4="15% YoY makes this one of fastest-growing east peripheral corridors" }
  @{ slug="safilguda"; name="Safilguda"; lat=17.451; lng=78.551; dLat=0.009; dLng=0.011; zone="East"; score=65; cat="Established"; infra=67; pop=68; sat=62; rera=58; emp=62; pv=62; gs=62; conn=70; amen=68; ecom=72; ent=60; green=38; pr="Rs4,000-6,500/sqft"; yoy=10; dc="partial"; sv=7; h1="Mid-segment residential between Malkajgiri and Secunderabad  -  consistent demand"; h2="Good TSRTC connectivity to ECIL and IT clusters at Uppal"; h3="New apartment supply absorbed within 6 months  -  low vacancy market"; h4="Mature colony with schools, hospitals within 2km ensures family retention" }
  @{ slug="pochampally"; name="Pochampally"; lat=17.331; lng=78.692; dLat=0.015; dLng=0.018; zone="East"; score=59; cat="Established"; infra=60; pop=55; sat=62; rera=48; emp=62; pv=58; gs=65; conn=52; amen=48; ecom=55; ent=42; green=55; pr="Rs1,800-3,500/sqft"; yoy=10; dc="partial"; sv=6; h1="Pochampally Ikat  -  GI-tagged handloom heritage, UNESCO Intangible Cultural Heritage"; h2="Telangana Handloom Village tourism project driving homestay and retail economy"; h3="Pharma corridor proximity along Hyderabad-Warangal highway creating employment"; h4="Heritage brand premium supports sustainable commercial value independent of IT cycle" }
  @{ slug="medipally"; name="Medipally"; lat=17.420; lng=78.605; dLat=0.015; dLng=0.018; zone="East"; score=68; cat="High Growth"; infra=70; pop=60; sat=72; rera=65; emp=75; pv=68; gs=70; conn=62; amen=55; ecom=65; ent=48; green=50; pr="Rs3,000-5,500/sqft"; yoy=16; dc="partial"; sv=7; h1="Pharma City anchor: Aurobindo, Dr Reddy adjacent Medipally industrial cluster"; h2="TS Pharma City project (19,000 acres) within 8km  -  largest pharma cluster in India"; h3="HMDA residential layouts fast-tracking to house 40,000+ pharma workers"; h4="16% YoY driven by Pharma City construction phase absorbing all supply" }
  @{ slug="raviryala"; name="Raviryala"; lat=17.300; lng=78.530; dLat=0.015; dLng=0.018; zone="East"; score=54; cat="Emerging"; infra=58; pop=48; sat=62; rera=48; emp=58; pv=52; gs=60; conn=50; amen=42; ecom=52; ent=35; green=55; pr="Rs1,500-3,200/sqft"; yoy=12; dc="partial"; sv=6; h1="South-east industrial: warehousing and FMCG distribution facilities cluster here"; h2="TSSIDC special economic zone land acquisition complete for food processing"; h3="ORR proximity at Hayathnagar interchange enables logistics tenant demand"; h4="Affordable south-east option attracting plotted development from Hayathnagar buyers" }
  @{ slug="annojiguda"; name="Annojiguda"; lat=17.456; lng=78.567; dLat=0.009; dLng=0.011; zone="East"; score=63; cat="Established"; infra=65; pop=62; sat=60; rera=55; emp=60; pv=60; gs=62; conn=68; amen=65; ecom=70; ent=58; green=38; pr="Rs3,800-6,500/sqft"; yoy=10; dc="partial"; sv=7; h1="ECIL and Secunderabad tech belt residential  -  stable government-private mix demand"; h2="Close to DRDO and DRDL establishments  -  defense research community housing"; h3="Well-established colony with complete civic infrastructure and amenities"; h4="Steady 10% appreciation driven by proximity to Secunderabad and ECIL corridors" }
  @{ slug="thumkunta"; name="Thumkunta"; lat=17.517; lng=78.585; dLat=0.015; dLng=0.018; zone="East"; score=62; cat="High Growth"; infra=65; pop=52; sat=68; rera=60; emp=65; pv=65; gs=68; conn=55; amen=48; ecom=60; ent=38; green=55; pr="Rs2,200-4,200/sqft"; yoy=16; dc="partial"; sv=6; h1="North-east logistics hub: cold chain, pharma distribution, FMCG warehousing"; h2="ORR junction at Kompally and Medchal access within 12 minutes"; h3="HMDA master plan notified industrial and residential zones both active"; h4="Dual demand: industrial land and workforce housing  -  16% YoY appreciation" }
  @{ slug="mailardevpally"; name="Mailardevpally"; lat=17.335; lng=78.520; dLat=0.012; dLng=0.014; zone="East"; score=49; cat="Emerging"; infra=52; pop=45; sat=55; rera=40; emp=48; pv=50; gs=55; conn=48; amen=40; ecom=52; ent=35; green=48; pr="Rs1,600-3,200/sqft"; yoy=12; dc="estimated"; sv=5; h1="South-east emerging zone: plotted development absorbing LB Nagar overflow"; h2="Close to Rajiv Gandhi International Airport via Hayathnagar-Shamshabad link"; h3="Budget segment demand consistent  -  first home buyers from IT outer ring"; h4="Infrastructure lag versus Hayathnagar keeps prices at 40% discount  -  catch-up play" }
  @{ slug="abdullapurmet"; name="Abdullapurmet"; lat=17.399; lng=78.640; dLat=0.018; dLng=0.022; zone="East"; score=51; cat="Emerging"; infra=55; pop=46; sat=58; rera=42; emp=48; pv=52; gs=60; conn=48; amen=40; ecom=50; ent=30; green=60; pr="Rs1,500-3,000/sqft"; yoy=13; dc="estimated"; sv=5; h1="Beyond Uppal  -  emerging east frontier of GHMC limits, plotted layouts active"; h2="Proposed Hyderabad Metro Phase 3 east extension through Abdullapurmet corridor"; h3="Telangana industrial policy notified 200-acre MSME cluster for this zone"; h4="Early-mover advantage: 13% YoY with full infrastructure still 3-4 years out" }
  # SOUTH (12)
  @{ slug="chevella"; name="Chevella"; lat=17.254; lng=77.802; dLat=0.020; dLng=0.025; zone="South"; score=44; cat="Emerging"; infra=48; pop=40; sat=50; rera=35; emp=38; pv=45; gs=52; conn=40; amen=35; ecom=42; ent=25; green=70; pr="Rs800-1,800/sqft"; yoy=12; dc="estimated"; sv=5; h1="Ranga Reddy district taluk center  -  administrative services hub for SW region"; h2="Ananthagiri Hills eco-zone creates tourism and weekend home demand"; h3="Very low base price: affordable agricultural-to-residential conversion plays active"; h4="45km from Hyderabad center  -  strictly long-horizon land banking, not end-use" }
  @{ slug="moinabad"; name="Moinabad"; lat=17.255; lng=78.108; dLat=0.018; dLng=0.022; zone="South"; score=55; cat="Emerging"; infra=58; pop=42; sat=62; rera=50; emp=42; pv=62; gs=65; conn=45; amen=40; ecom=48; ent=42; green=72; pr="Rs1,800-4,500/sqft"; yoy=15; dc="partial"; sv=6; h1="Resort and villa corridor 25km SW of Hyderabad  -  weekend home demand high"; h2="Ananthagiri Forest Reserve creates strict eco-zone buffer  -  supply-capped land"; h3="Luxury farmhouse and gated resort development active along NH 65 belt"; h4="15% YoY premium over rural south average driven by HNI weekend retreat demand" }
  @{ slug="manchirevula"; name="Manchirevula"; lat=17.321; lng=78.332; dLat=0.012; dLng=0.014; zone="South"; score=61; cat="High Growth"; infra=65; pop=50; sat=68; rera=58; emp=52; pv=68; gs=65; conn=58; amen=48; ecom=60; ent=45; green=58; pr="Rs3,200-6,500/sqft"; yoy=18; dc="partial"; sv=6; h1="Narsingi adjacent  -  HMDA master plan catchment for Outer Ring Road residential growth"; h2="Major IT parks at Nanakramguda within 5km drive workforce housing demand"; h3="Gated community launches: 4 major projects launched 2024-26 on Manchirevula Road"; h4="18% YoY  -  fastest south corridor outside Financial District and Narsingi" }
  @{ slug="kismatpur"; name="Kismatpur"; lat=17.280; lng=78.440; dLat=0.015; dLng=0.018; zone="South"; score=58; cat="Emerging"; infra=62; pop=48; sat=65; rera=52; emp=50; pv=62; gs=65; conn=52; amen=42; ecom=55; ent=38; green=55; pr="Rs1,800-4,000/sqft"; yoy=15; dc="partial"; sv=6; h1="South corridor near RGIA  -  airport-adjacent real estate benefiting from aviation demand"; h2="Hyderabad Pharma City ring road passes through Kismatpur corridor"; h3="HMDA expansion zone: residential and warehousing layouts being approved"; h4="Strong 15% appreciation momentum as airport proximity premium spreads southward" }
  @{ slug="peerancheru"; name="Peerancheru"; lat=17.305; lng=78.487; dLat=0.012; dLng=0.014; zone="South"; score=47; cat="Emerging"; infra=50; pop=42; sat=52; rera=38; emp=42; pv=45; gs=55; conn=48; amen=38; ecom=50; ent=32; green=52; pr="Rs1,500-3,200/sqft"; yoy=10; dc="estimated"; sv=5; h1="South of Falaknuma  -  old city south expansion into peri-urban zone"; h2="Decent road access via Falaknuma-Kishanbagh Road to city center"; h3="Budget plotted development active  -  first-home buyers from Falaknuma area"; h4="Infrastructure investment needed before mass residential absorption" }
  @{ slug="shabad"; name="Shabad"; lat=17.219; lng=78.370; dLat=0.018; dLng=0.022; zone="South"; score=48; cat="Emerging"; infra=52; pop=42; sat=55; rera=38; emp=42; pv=48; gs=55; conn=42; amen=38; ecom=48; ent=28; green=60; pr="Rs900-2,200/sqft"; yoy=11; dc="estimated"; sv=5; h1="South Ranga Reddy satellite town  -  NH 44 (Hyderabad-Bangalore highway) access"; h2="TSSIDC industrial zone land parcels in Shabad Mandal attracting manufacturing"; h3="Budget land banking destination: 40% discount to Shamshabad prices"; h4="Shadnagar growth momentum spreading northward through this corridor" }
  @{ slug="farooknagar"; name="Farooknagar"; lat=17.224; lng=78.258; dLat=0.018; dLng=0.022; zone="South"; score=51; cat="Emerging"; infra=55; pop=45; sat=58; rera=42; emp=55; pv=50; gs=60; conn=45; amen=40; ecom=50; ent=32; green=62; pr="Rs900-2,000/sqft"; yoy=12; dc="estimated"; sv=5; h1="Defense Research and Development Organization (DRDO) missile testing range nearby"; h2="NH 65 (Hyderabad-Pune) access supports light industrial and logistics use"; h3="Historical saltpan lakes  -  Farooknagar Lake an ecological tourism asset"; h4="Low prices and strategic NH access attract industrial land buyers over residential" }
  @{ slug="sultanpur-jagir"; name="Sultanpur Jagir"; lat=17.151; lng=78.379; dLat=0.020; dLng=0.025; zone="South"; score=42; cat="Emerging"; infra=45; pop=38; sat=48; rera=32; emp=35; pv=40; gs=50; conn=38; amen=32; ecom=42; ent=22; green=65; pr="Rs600-1,500/sqft"; yoy=10; dc="estimated"; sv=4; h1="Deep south Ranga Reddy  -  agricultural land transitioning under HMDA expansion"; h2="50km from city center  -  strictly 7-10 year investment horizon"; h3="Proposed TSRTC bus route extension will improve access from Shadnagar"; h4="Lowest price point in Hyderabad metro region  -  pure land speculation play" }
  @{ slug="kandukur-rr"; name="Kandukur (RR)"; lat=17.108; lng=78.245; dLat=0.020; dLng=0.025; zone="South"; score=41; cat="Emerging"; infra=44; pop=36; sat=46; rera=30; emp=34; pv=38; gs=48; conn=35; amen=30; ecom=40; ent=20; green=68; pr="Rs500-1,200/sqft"; yoy=9; dc="estimated"; sv=4; h1="Ranga Reddy district boundary  -  very early stage peri-urban land"; h2="Proposed NH expansion through Kandukur Mandal under NHAI Phase 4"; h3="Agricultural land dominant  -  JDA and HMDA layout approvals sparse"; h4="Extreme long-horizon play: 10+ years to meaningful residential absorption" }
  @{ slug="rajapally"; name="Rajapally"; lat=17.192; lng=78.445; dLat=0.018; dLng=0.022; zone="South"; score=44; cat="Emerging"; infra=46; pop=40; sat=50; rera=34; emp=38; pv=42; gs=52; conn=42; amen=35; ecom=46; ent=25; green=62; pr="Rs800-2,000/sqft"; yoy=11; dc="estimated"; sv=5; h1="South of Shamshabad  -  airport corridor halo spreading price inflation southward"; h2="HMDA master plan designates corridor for warehousing and cold chain logistics"; h3="Proposed Hyderabad Metro Airport Express spur feasibility study includes area"; h4="Budget entry into airport-adjacent south corridor with 5-7 year return horizon" }
  @{ slug="shivrampally"; name="Shivrampally"; lat=17.363; lng=78.403; dLat=0.012; dLng=0.014; zone="South"; score=56; cat="Emerging"; infra=60; pop=52; sat=62; rera=50; emp=50; pv=58; gs=60; conn=55; amen=48; ecom=58; ent=45; green=52; pr="Rs2,500-5,000/sqft"; yoy=13; dc="partial"; sv=6; h1="South of Tolichowki  -  HMDA layout demand from Mehdipatnam IT workers"; h2="Proposed ORR spur connecting Shivrampally to outer ring improving accessibility"; h3="Multiple RERA-registered projects completed 2023-25 absorbing mid-segment demand"; h4="Affordable alternative to Attapur and Manikonda with 13% YoY momentum" }
  @{ slug="pedda-golconda"; name="Pedda Golconda"; lat=17.265; lng=78.382; dLat=0.015; dLng=0.018; zone="South"; score=50; cat="Emerging"; infra=52; pop=42; sat=55; rera=42; emp=45; pv=52; gs=58; conn=48; amen=40; ecom=52; ent=35; green=55; pr="Rs1,200-2,800/sqft"; yoy=12; dc="estimated"; sv=5; h1="SW of Shamshabad near airport  -  early-mover residential layouts active"; h2="Hyderabad Pharma City ring road passes 4km east creating land value uplift"; h3="NH 44 frontage plots attracting commercial and truck logistics operators"; h4="Airport proximity premium expected to increase as RGIA capacity doubles by 2028" }
  # WEST (8)
  @{ slug="ramachandrapuram"; name="Ramachandrapuram"; lat=17.486; lng=78.270; dLat=0.015; dLng=0.018; zone="West"; score=60; cat="Established"; infra=63; pop=55; sat=65; rera=55; emp=62; pv=58; gs=62; conn=58; amen=52; ecom=62; ent=45; green=48; pr="Rs2,500-5,000/sqft"; yoy=12; dc="partial"; sv=6; h1="West industrial township: IDA Patancheru overflow and APIIC industrial estates"; h2="ORR junction at Patancheru provides fast access to Hitech City in 25 minutes"; h3="Working population housing: consistent demand from Patancheru IIE workers"; h4="12% YoY driven by IT west corridor expansion toward Ramachandrapuram" }
  @{ slug="muthangi"; name="Muthangi"; lat=17.476; lng=78.254; dLat=0.015; dLng=0.018; zone="West"; score=58; cat="Emerging"; infra=60; pop=50; sat=65; rera=52; emp=62; pv=58; gs=62; conn=55; amen=45; ecom=58; ent=38; green=52; pr="Rs2,000-4,500/sqft"; yoy=14; dc="partial"; sv=6; h1="West of Patancheru  -  HMDA township expansion absorbing IIE workforce"; h2="Muthangi Phase 2 HMDA layout approvals issued 2024  -  2,500 plots live"; h3="Close to APIIC Patancheru Industrial Estate and Special Economic Zone"; h4="14% YoY with strong RERA registration activity confirms end-user demand" }
  @{ slug="narsapur-ts"; name="Narsapur (TS)"; lat=17.499; lng=78.200; dLat=0.020; dLng=0.025; zone="West"; score=52; cat="Emerging"; infra=55; pop=45; sat=58; rera=45; emp=48; pv=52; gs=60; conn=48; amen=40; ecom=50; ent=30; green=58; pr="Rs1,200-2,800/sqft"; yoy=13; dc="estimated"; sv=5; h1="Western frontier town  -  NH 65 access and Medak district fringe land banking"; h2="Proposed Hyderabad-Pune Expressway alignment passes through Narsapur Mandal"; h3="HMDA master plan recently extended to cover Narsapur jurisdiction"; h4="Agricultural land conversion ongoing  -  3-5 year horizon for residential absorption" }
  @{ slug="vikarabad"; name="Vikarabad"; lat=17.338; lng=77.906; dLat=0.025; dLng=0.030; zone="West"; score=45; cat="Emerging"; infra=48; pop=42; sat=52; rera=38; emp=40; pv=45; gs=55; conn=40; amen=38; ecom=44; ent=30; green=72; pr="Rs600-1,500/sqft"; yoy=10; dc="estimated"; sv=4; h1="Ranga Reddy district western HQ  -  administrative and judicial center"; h2="Ananthagiri Hills and Vikarabad Deer Park create eco-tourism economy"; h3="55km from Hyderabad via NH 65  -  emerging as weekend home and nature retreat zone"; h4="Extremely low base price: farmhouse and plotted development under Rs1,500/sqft" }
  @{ slug="koheda"; name="Koheda"; lat=17.516; lng=78.338; dLat=0.015; dLng=0.018; zone="West"; score=56; cat="Emerging"; infra=60; pop=48; sat=62; rera=52; emp=52; pv=58; gs=62; conn=52; amen=42; ecom=55; ent=32; green=55; pr="Rs1,800-3,800/sqft"; yoy=14; dc="partial"; sv=6; h1="NW Hyderabad: ORR access and Ameenpur growth front spreading into Koheda"; h2="Close to IDA Pashamylaram industrial cluster  -  workforce housing demand rising"; h3="HMDA layout activity accelerating with 3 registered projects in 2024-25"; h4="14% YoY supported by industrial employment base and improving road access" }
  @{ slug="sanath-nagar"; name="Sanath Nagar"; lat=17.463; lng=78.440; dLat=0.010; dLng=0.012; zone="West"; score=64; cat="Established"; infra=67; pop=62; sat=62; rera=58; emp=70; pv=60; gs=62; conn=70; amen=62; ecom=72; ent=58; green=38; pr="Rs3,500-6,000/sqft"; yoy=10; dc="partial"; sv=7; h1="West Hyderabad industrial-residential: BHEL, Alstom and Siemens plant workers base"; h2="Good connectivity to Hitech City (12km) and old Hyderabad center (8km)"; h3="Mature colony: hospitals, schools, markets fully developed"; h4="Stable blue-collar and mid-segment demand from manufacturing sector employees" }
  @{ slug="srinagar-colony"; name="Srinagar Colony"; lat=17.431; lng=78.441; dLat=0.010; dLng=0.012; zone="West"; score=68; cat="Established"; infra=70; pop=68; sat=65; rera=62; emp=65; pv=68; gs=65; conn=72; amen=70; ecom=76; ent=68; green=42; pr="Rs5,000-8,500/sqft"; yoy=11; dc="partial"; sv=7; h1="Central-west premium residential: 500m from Ameerpet Metro, walkability score high"; h2="Dense F&B and retail corridor on Srinagar Colony Main Road  -  lifestyle hub"; h3="Strong NRI and returning diaspora demand for resale apartments"; h4="11% YoY driven by Ameerpet junction central location premium" }
  @{ slug="pedda-shankarampet"; name="Pedda Shankarampet"; lat=17.465; lng=78.265; dLat=0.018; dLng=0.022; zone="West"; score=54; cat="Emerging"; infra=55; pop=42; sat=60; rera=45; emp=45; pv=55; gs=62; conn=48; amen=38; ecom=50; ent=28; green=60; pr="Rs1,200-2,800/sqft"; yoy=13; dc="estimated"; sv=5; h1="Far west residential township fringe: HMDA expansion plots under Rs3,000/sqft"; h2="Drinking water supply pipeline from Manjira extended to this mandal in 2024"; h3="Agricultural land conversion underway  -  layout approvals increasing year on year"; h4="Long-horizon play adjacent to Patancheru industrial corridor growth vector" }
)

# Zone slug lists for cluster update
$zoneAssign = @{
  "Central" = @("charminar","afzalgunj","sultan-bazaar","hussaini-alam","yakutpura","chaderghat","moghalpura","bahadurpura","rein-bazaar","dabirpura","aghapura")
  "North"   = @("warasiguda","tirumalagiri","mettuguda","karkhana","west-marredpally","mahendra-hills","shamirpet","gundlapochampally","bonthapally","turkapally","keesaragutta","pashamylaram")
  "East"    = @("nagole","jawaharnagar","rampally","safilguda","pochampally","medipally","raviryala","annojiguda","thumkunta","mailardevpally","abdullapurmet")
  "South"   = @("chevella","moinabad","manchirevula","kismatpur","peerancheru","shabad","farooknagar","sultanpur-jagir","kandukur-rr","rajapally","shivrampally","pedda-golconda")
  "West"    = @("ramachandrapuram","muthangi","narsapur-ts","vikarabad","koheda","sanath-nagar","srinagar-colony","pedda-shankarampet")
}

# ─── 1. BUILD LOCALITY JSON ENTRIES ───────────────────────────────────────────
$existingLoc = Get-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\localities.json" -Raw
$existingLoc = $existingLoc.TrimEnd()
if ($existingLoc.EndsWith(']')) { $existingLoc = $existingLoc.Substring(0, $existingLoc.Length - 1).TrimEnd() }

$locEntries = foreach ($loc in $newLocalities) {
  $poly = Build-PolyJson $loc.lat $loc.lng $loc.dLat $loc.dLng
  "  {$($NL)    `"slug`": `"$($loc.slug)`",$($NL)    `"name`": `"$($loc.name)`",$($NL)    `"center`": [$($loc.lat), $($loc.lng)],$($NL)    `"polygon`": $poly$($NL)  }"
}
$newLocJson = $existingLoc.TrimEnd(',') + ',' + $NL + ($locEntries -join ",$NL") + $NL + ']'
Set-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\localities.json" $newLocJson -Encoding utf8
Write-Host "localities.json: $(($newLocJson | Select-String '"slug"').Matches.Count) entries"

# ─── 2. UPDATE CLUSTERS.JSON ──────────────────────────────────────────────────
$clusters = Get-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\clusters.json" | ConvertFrom-Json
foreach ($cluster in $clusters) {
  $zoneName = $cluster.zone
  if ($zoneAssign.ContainsKey($zoneName)) {
    $cluster.localitySlugs = @($cluster.localitySlugs) + $zoneAssign[$zoneName]
  }
}
$clusters | ConvertTo-Json -Depth 4 | Set-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\clusters.json" -Encoding utf8
Write-Host "clusters.json updated"

# ─── 3. UPDATE ALIASES.JSON ──────────────────────────────────────────────────
$aliases = Get-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\aliases.json" | ConvertFrom-Json
$aliasHash = @{}
$aliases.PSObject.Properties | ForEach-Object { $aliasHash[$_.Name] = $_.Value }
foreach ($loc in $newLocalities) {
  $words = $loc.name.ToLower() -replace '[^a-z0-9 ]',''
  $aliasHash[$loc.slug] = @($loc.name.ToLower(), $words) | Select-Object -Unique
}
$aliasHash | ConvertTo-Json -Depth 3 | Set-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\data\cities\hyderabad\aliases.json" -Encoding utf8
Write-Host "aliases.json updated"

# ─── 4. APPEND MICROMARKETS TO HYDERABAD.TS ──────────────────────────────────
$tsEntries = foreach ($loc in $newLocalities) {
  $sigStr = '"infrastructure": {0}, "population": {1}, "satellite": {2}, "rera": {3}, "employment": {4}, "priceVelocity": {5}, "govtScheme": {6}' -f $loc.infra,$loc.pop,$loc.sat,$loc.rera,$loc.emp,$loc.pv,$loc.gs
  $livStr = '"connectivity": {0}, "amenities": {1}, "ecommerce": {2}, "entertainment": {3}, "greenSpaces": {4}' -f $loc.conn,$loc.amen,$loc.ecom,$loc.ent,$loc.green
  $lines = @(
    '  {',
    ('    ...locality("' + $loc.slug + '"),'),
    ('    "score": ' + $loc.score + ','),
    ('    "category": "' + $loc.cat + '",'),
    ('    "signals": { ' + $sigStr + ' },'),
    ('    "livability": { ' + $livStr + ' },'),
    '    "highlights": [',
    ('      "' + $loc.h1 + '",'),
    ('      "' + $loc.h2 + '",'),
    ('      "' + $loc.h3 + '",'),
    ('      "' + $loc.h4 + '"'),
    '    ],',
    ('    "priceRange": "' + $loc.pr + '",'),
    ('    "yoy": ' + $loc.yoy + ','),
    ('    "dataConfidence": "' + $loc.dc + '",'),
    '    "dataAsOf": "2026-05-01",',
    ('    "signalsAvailable": ' + $loc.sv),
    '  }'
  )
  $lines -join $NL
}

$content = Get-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\frontend\src\data\hyderabad.ts" -Raw
$exportIdx = $content.IndexOf('export const cityMeta')
$beforeExport = $content.Substring(0, $exportIdx)
$afterExport  = $content.Substring($exportIdx)
$closeBracket = $beforeExport.LastIndexOf(']')
$insertBefore = $beforeExport.Substring(0, $closeBracket)
$insertAfter  = $beforeExport.Substring($closeBracket)
$newEntriesStr = $tsEntries -join (',' + $NL)
$newContent = $insertBefore + ',' + $NL + $newEntriesStr + $NL + $insertAfter + $afterExport
Set-Content "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\frontend\src\data\hyderabad.ts" $newContent -Encoding utf8

$finalCount = (Select-String -Path "C:\Users\Naveen\OneDrive\Desktop\PlotDNA\frontend\src\data\hyderabad.ts" -Pattern '\.\.\.locality\(').Count
Write-Host "hyderabad.ts: $finalCount total locality entries"
